#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UrbanGame.Droid.Resource", IsApplication=true)]

namespace UrbanGame.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::UrbanGame.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::UrbanGame.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::UrbanGame.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::UrbanGame.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::UrbanGame.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::UrbanGame.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::UrbanGame.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::UrbanGame.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::UrbanGame.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::UrbanGame.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::UrbanGame.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::UrbanGame.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::UrbanGame.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::UrbanGame.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::UrbanGame.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::UrbanGame.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::UrbanGame.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::UrbanGame.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::UrbanGame.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::UrbanGame.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::UrbanGame.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.ApplicationName = global::UrbanGame.Droid.Resource.String.ApplicationName;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.Hello = global::UrbanGame.Droid.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::UrbanGame.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::UrbanGame.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::UrbanGame.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int answer_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int aboutAuthorsButton = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int aboutTreasureButton = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int advanceObjectiveButton = 2131034120;
			
			// aapt resource value: 0x7f05001f
			public const int answersRadioGroup = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int contentFrame = 2131034145;
			
			// aapt resource value: 0x7f05001a
			public const int currentObjectiveStepTextView = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int currentObjectiveTextView = 2131034131;
			
			// aapt resource value: 0x7f050006
			public const int gamePageRoot = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int howToPlayButton = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int landingPageButtonGroup = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int landingPageButtonGroupRoot = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int landingPageRoot = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050016
			public const int nextObjectiveButton = 2131034134;
			
			// aapt resource value: 0x7f05001d
			public const int nextObjectiveStepButton = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int numberOfObjectiveStepsTextView = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int numberOfObjectivesTextView = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int objectiveDisplayRoot = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int objectiveNavigationFragment = 2131034115;
			
			// aapt resource value: 0x7f050014
			public const int objectiveSeparatorTextView = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int objectiveStepDisplayRoot = 2131034136;
			
			// aapt resource value: 0x7f050004
			public const int objectiveStepNavigationContainer = 2131034116;
			
			// aapt resource value: 0x7f05001b
			public const int objectiveStepSeparatorTextView = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int objectiveStepTextView = 2131034137;
			
			// aapt resource value: 0x7f050005
			public const int objectiveStepViewContainer = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int objectiveTextView = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int previousObjectiveButton = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int previousObjectiveStepButton = 2131034135;
			
			// aapt resource value: 0x7f05001e
			public const int questionTextView = 2131034142;
			
			// aapt resource value: 0x7f050007
			public const int restGameButton = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int startGameButton = 2131034124;
			
			// aapt resource value: 0x7f050020
			public const int textObjectiveStepContent = 2131034144;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_objectivenavigation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_objectivestepnavigation = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_objectivestepview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_questionobjectivestep = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_textobjectivestep = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int item_answer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int splash_screen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscanneractivitylayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscannerfragmentlayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int AnswerButton = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int UrbanGameAppStyle = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
